### ISSUE TITLE
Getting Socket error 

### ISSUE THREAD

**Issue by smednikar** [microsoftgraph/msgraph-training-pythondjangoapp#37]
On the visual studio code terminal , i see below socket error, when the screen is on outlook Stay signed in?

----------------------------------------------------------------------------------------------------------------------------
[15/Sep/2020 21:49:05] "GET /signin HTTP/1.1" 302 0
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61248)
Exception happened during processing of request from ('127.0.0.1', 61247)
Traceback (most recent call last):
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socketserver.py", line 720, in __init__
    self.handle()
Traceback (most recent call last):
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socketserver.py", line 720, in __init__
    self.handle()
----------------------------------------
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\django\core\servers\basehttp.py", line 172, in handle
    self.handle_one_request()
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\smednika\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
![outlook](https://user-images.githubusercontent.com/70968055/93237421-b3ff4a80-f79d-11ea-9327-2d978a38e3a9.png)

**Comment by jasonjoh** [comment]
Is this causing the app to fail?

**Comment by smednikar** [comment]
No.. able to send from my website.. Also getting this below error, when tried to refresh the token after expiry  . 
-------------------------------------------------
[17/Sep/2020 20:34:47] "POST /emailreceipt HTTP/1.1" 200 55
Internal Server Error: /emailreceipt
Traceback (most recent call last):
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MSG Projects\MSGgbs_app\paymentDocs\views.py", line 73, in emailreceipt
    responseMail = send_email(request, body = mailBody)
  File "D:\MSG Projects\MSGgbs_app\paymentDocs\ComposeEmail.py", line 9, in send_email
    atoken = get_token(request)
  File "D:\MSG Projects\MSGgbs_app\MSAccessToken\auth_helper.py", line 85, in get_token
    new_token = aad_auth.refresh_token(token_url, **refresh_params)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\requests_oauthlib\oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Users\smednika\Envs\MSGproject\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_token'.
Trace ID: ca58fd14-eebb-42ad-ae8f-4b04231bd800
Correlation ID: c2d21021-d4c7-48f6-b5ce-a9da1f2ff936
Timestamp: 2020-09-17 16:09:37Z
[17/Sep/2020 21:41:37] "POST /emailreceipt HTTP/1.1" 500 117729
------------------------------------------------------------

{
  "token_type": "Bearer",
  "scope": [
    "User.Read",
    "Mail.Send"
  ],
  "expires_in": 3600,
  "ext_expires_in": 3600,
  "access_token": "EwCAA8l6BAAUO9chh8cJscQLmU...............WwUpCxt+7Ua7h8Um12lnhGuz0gKsrRwgMwo8gejQI=",
  "expires_at": 1600275524.7675874
}
---------------------------

**Comment by jasonjoh** [comment]
Do you have the `offline_access` scope in your initial authorization URL? The error indicates you don't have a refresh token.

**Comment by smednikar** [comment]
Thank you. After adding offline_access to scope, able to get the refresh token

**Comment by jasonjoh** [comment]
Glad to hear that fixed it.
